name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  SwiftLint:
    runs-on: macOS-Latest

    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3
      
      - name: Check For Swiftlint
        run: swiftlint help
